src/Entity/Etudiant.php
<?php

namespace App\Entity;

use App\Repository\EtudiantRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: EtudiantRepository::class)]
class Etudiant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
    

    #[ORM\ManyToOne(inversedBy: 'etudiants')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Filiere $filiere = null;

    #[ORM\OneToOne(mappedBy: 'etudiant', cascade: ['persist', 'remove'])]
    private ?Compte $compte = null;
    
    #[ORM\Column(length: 255)]
    private ?string $cne = null;

    #[ORM\Column(length: 255)]
    private ?string $cin = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;
    
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_Naissance = null;

    #[ORM\Column(length: 255)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $genre = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse_postale = null;

    #[ORM\Column(length: 255)]
    private ?string $nationalite = null;

    #[ORM\Column(length: 255)]
    private ?string $profession_pere = null;

    #[ORM\Column(length: 255)]
    private ?string $profession_mere = null;

    #[ORM\Column(length: 255)]
    private ?string $gsm_mere = null;

    #[ORM\Column(length: 255)]
    private ?string $gsm_pere = null;

    #[ORM\Column(length: 255)]
    private ?string $mot_passe = null;
    private ?string $confirmPass = null;
   
    #[ORM\Column(nullable: true)]
    private ?bool $status = null;

    #[ORM\Column(length: 255)]
    private ?string $niveau = null;

    #[ORM\Column(length: 255)]
    private ?string $note_math = null;

    #[ORM\Column(length: 255)]
    private ?string $note_franc = null;

    #[ORM\Column(length: 255)]
    private ?string $note_6eme = null;

    #[ORM\Column(length: 255)]
    private ?string $note_bac = null;


    #[ORM\Column(length: 255,nullable: true)]
    private ?string $Attestation_reussite = null;
    
    #[ORM\Column(length: 255,nullable: true)]
    private ?string $carte_nationale = null;
    
    #[ORM\Column(length: 255,nullable: true)]
    private ?string $Attestation_reussite1 = null;
    
    #[ORM\Column(length: 255,nullable: true)]
    private ?string $Attestation_reussite2 = null;
    
    #[ORM\Column(length: 255,nullable: true)]
    private ?string $licence = null;
    
    #[ORM\Column(length: 255,nullable: true)]
    private ?string $Attestation_reussite4 = null;
    
    public function getConfirmPass(): ?string
    {
        return $this->confirmPass;
    }
    public function setConfirmPass(string $confirmPass): void
    {
        $this->confirmPass = $confirmPass;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFiliere(): ?Filiere
    {
        return $this->filiere;
    }

    public function setFiliere(?Filiere $filiere): static
    {
        $this->filiere = $filiere;

        return $this;
    }

    public function getCompte(): ?Compte
    {
        return $this->compte;
    }

    public function setCompte(?Compte $compte): static
    {
        // unset the owning side of the relation if necessary
        if ($compte === null && $this->compte !== null) {
            $this->compte->setEtudiant(null);
        }

        // set the owning side of the relation if necessary
        if ($compte !== null && $compte->getEtudiant() !== $this) {
            $compte->setEtudiant($this);
        }

        $this->compte = $compte;

        return $this;
    }

   

    public function getCne(): ?string
    {
        return $this->cne;
    }

    public function setCne(string $cne): static
    {
        $this->cne = $cne;

        return $this;
    }

    public function getCin(): ?string
    {
        return $this->cin;
    }

    public function setCin(string $cin): static
    {
        $this->cin = $cin;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
{
    return $this->date_Naissance;
}

public function setDateNaissance(?\DateTimeInterface $date_Naissance): static
{
    $this->date_Naissance = $date_Naissance;

    return $this;
}

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): static
    {
        $this->genre = $genre;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAdressePostale(): ?string
    {
        return $this->adresse_postale;
    }

    public function setAdressePostale(string $adresse_postale): static
    {
        $this->adresse_postale = $adresse_postale;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): static
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    public function getProfessionPere(): ?string
    {
        return $this->profession_pere;
    }

    public function setProfessionPere(string $profession_pere): static
    {
        $this->profession_pere = $profession_pere;

        return $this;
    }

    public function getProfessionMere(): ?string
    {
        return $this->profession_mere;
    }

    public function setProfessionMere(string $profession_mere): static
    {
        $this->profession_mere = $profession_mere;

        return $this;
    }

    public function getGsmMere(): ?string
    {
        return $this->gsm_mere;
    }

    public function setGsmMere(string $gsm_mere): static
    {
        $this->gsm_mere = $gsm_mere;

        return $this;
    }

    public function getGsmPere(): ?string
    {
        return $this->gsm_pere;
    }

    public function setGsmPere(string $gsm_pere): static
    {
        $this->gsm_pere = $gsm_pere;

        return $this;
    }

    public function getMotPasse(): ?string
    {
        return $this->mot_passe;
    }

    public function setMotPasse(string $mot_passe): static
    {
        $this->mot_passe = $mot_passe;

        return $this;
    }

   

    public function isStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(?bool $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getNiveau(): ?string
    {
        return $this->niveau;
    }

    public function setNiveau(string $niveau): static
    {
        $this->niveau = $niveau;

        return $this;
    }

    public function getNoteMath(): ?string
    {
        return $this->note_math;
    }

    public function setNoteMath(string $note_math): static
    {
        $this->note_math = $note_math;

        return $this;
    }

    public function getNoteFranc(): ?string
    {
        return $this->note_franc;
    }

    public function setNoteFranc(string $note_franc): static
    {
        $this->note_franc = $note_franc;

        return $this;
    }

    public function getNote6eme(): ?string
    {
        return $this->note_6eme;
    }

    public function setNote6eme(string $note_6eme): static
    {
        $this->note_6eme = $note_6eme;

        return $this;
    }

    public function getNoteBac(): ?string
    {
        return $this->note_bac;
    }

    public function setNoteBac(string $note_bac): static
    {
        $this->note_bac = $note_bac;

        return $this;
    }

    public function getAttestationReussite(): ?string
    {
        return $this->Attestation_reussite;
    }

    public function setAttestationReussite(string $Attestation_reussite): static
    {
        $this->Attestation_reussite = $Attestation_reussite;

        return $this;
    }

    public function getCarteNationale(): ?string
    {
        return $this->carte_nationale;
    }

    public function setCarteNationale(string $carte_nationale): static
    {
        $this->carte_nationale = $carte_nationale;

        return $this;
    }

    public function getAttestationReussite1(): ?string
    {
        return $this->Attestation_reussite1;
    }

    public function setAttestationReussite1(?string $Attestation_reussite1): static
    {
        $this->Attestation_reussite1 = $Attestation_reussite1;

        return $this;
    }

    public function getAttestationReussite2(): ?string
    {
        return $this->Attestation_reussite2;
    }

    public function setAttestationReussite2(?string $Attestation_reussite2): static
    {
        $this->Attestation_reussite2 = $Attestation_reussite2;

        return $this;
    }

    public function getLicence(): ?string
    {
        return $this->licence;
    }

    public function setLicence(?string $licence): static
    {
        $this->licence = $licence;

        return $this;

src/Controller/EtudiantController.php
<?php

namespace App\Controller;

use App\Entity\Etudiant;
use App\Form\EtudiantType;
use App\Repository\EtudiantRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/etudiant')]
class EtudiantController extends AbstractController
{
    #[Route('/', name: 'app_etudiant_index', methods: ['GET'])]
    public function index(EtudiantRepository $etudiantRepository): Response
    {
        return $this->render('etudiant/index.html.twig', [
            'etudiants' => $etudiantRepository->findAll(),
        ]);
    }

    // #[Route('/new', name: 'app_etudiant_new', methods: ['GET', 'POST'])]
    // public function new(Request $request, EntityManagerInterface $entityManager): Response
    // {
    //     $etudiant = new Etudiant();
    //     $form = $this->createForm(EtudiantType::class, $etudiant);
    //     $form->handleRequest($request);

    //     if ($form->isSubmitted() && $form->isValid()) {
    //         $entityManager->persist($etudiant);
    //         $entityManager->flush();

    //         return $this->redirectToRoute('app_etudiant_index', [], Response::HTTP_SEE_OTHER);
    //     }

    //     return $this->render('etudiant/new.html.twig', [
    //         'etudiant' => $etudiant,
    //         'form' => $form,
    //     ]);
    // }

    #[Route('/new', name: 'app_etudiant_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $etudiant = new Etudiant();
        $form = $this->createForm(EtudiantType::class, $etudiant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Attestation de Réussite
            $this->handleFileUpload($form, 'Attestation_reussite', 'setAttestationReussite', $etudiant);

            // Carte Nationale
            $this->handleFileUpload($form, 'carte_nationale', 'setCarteNationale', $etudiant);

            // Attestation de Réussite 1
            $this->handleFileUpload($form, 'Attestation_reussite1', 'setAttestationReussite1', $etudiant);

            // Attestation de Réussite 2
            $this->handleFileUpload($form, 'Attestation_reussite2', 'setAttestationReussite2', $etudiant);

            // Licence
            $this->handleFileUpload($form, 'licence', 'setLicence', $etudiant);

            // Attestation de Réussite 4
            $this->handleFileUpload($form, 'Attestation_reussite4', 'setAttestationReussite4', $etudiant);

            $entityManager->persist($etudiant);
            $entityManager->flush();

            return $this->redirectToRoute('app_etudiant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('etudiant/new.html.twig', [
            'etudiant' => $etudiant,
            'form' => $form,
        ]);
    }

    private function handleFileUpload($form, $fieldName, $setterMethod, $etudiant)
    {
        $file = $form->get($fieldName)->getData();
        if ($file instanceof UploadedFile) {
            $uploadsDirectory=$this->getParameter('kernel.project_dir') . '/public/uploads';
            $file->move($uploadsDirectory,$file->getClientOriginalName());
            $etudiant->$setterMethod($uploadsDirectory . '/' . $file->getClientOriginalName());
            
        }
    }

    #[Route('/{id}', name: 'app_etudiant_show', methods: ['GET'])]
    public function show(Etudiant $etudiant): Response
    {
        return $this->render('etudiant/show.html.twig', [
            'etudiant' => $etudiant,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_etudiant_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Etudiant $etudiant, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EtudiantType::class, $etudiant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_etudiant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('etudiant/edit.html.twig', [
            'etudiant' => $etudiant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_etudiant_delete', methods: ['POST'])]
    public function delete(Request $request, Etudiant $etudiant, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$etudiant->getId(), $request->request->get('_token'))) {
            $entityManager->remove($etudiant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_etudiant_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/etudiant/_delete_form.html.twig
<form method="post" action="{{ path('app_etudiant_delete', {'id': etudiant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ etudiant.id) }}">
    <button class="btn">Delete</button>
</form>

templates/etudiant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etudiant index{% endblock %}

{% block body %}
    <h1>Etudiant index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Status</th>
                <th>Cne</th>
                <th>Cin</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Date_Naissance</th>
                <th>Telephone</th>
                <th>Email</th>
                <th>Genre</th>
                <th>Ville</th>
                <th>Adresse_postale</th>
                <th>Nationalite</th>
                <th>Profession_pere</th>
                <th>Profession_mere</th>
                <th>Gsm_mere</th>
                <th>Gsm_pere</th>
                <th>Mot_passe</th>
                <th>Confirm_pass</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for etudiant in etudiants %}
            <tr>
                <td>{{ etudiant.id }}</td>
                <td>{{ etudiant.status ? 'Yes' : 'No' }}</td>
                <td>{{ etudiant.cne }}</td>
                <td>{{ etudiant.cin }}</td>
                <td>{{ etudiant.nom }}</td>
                <td>{{ etudiant.prenom }}</td>
                <td>{{ etudiant.dateNaissance ? etudiant.dateNaissance|date('Y-m-d') : '' }}</td>
                <td>{{ etudiant.telephone }}</td>
                <td>{{ etudiant.email }}</td>
                <td>{{ etudiant.genre }}</td>
                <td>{{ etudiant.ville }}</td>
                <td>{{ etudiant.adressePostale }}</td>
                <td>{{ etudiant.nationalite }}</td>
                <td>{{ etudiant.professionPere }}</td>
                <td>{{ etudiant.professionMere }}</td>
                <td>{{ etudiant.gsmMere }}</td>
                <td>{{ etudiant.gsmPere }}</td>
                <td>{{ etudiant.motPasse }}</td>
                <td>{{ etudiant.ConfirmPass }}</td>
                <td>
                    <a href="{{ path('app_etudiant_show', {'id': etudiant.id}) }}">show</a>
                    <a href="{{ path('app_etudiant_edit', {'id': etudiant.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="20">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_etudiant_new') }}">Create new</a>
{% endblock %}

templates/etudiant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %} Ajouter Etudiant {% endblock %}

{% block body %}

    <div class="auth option2">
        <div class="auth_left">
            <div class="card">
                <div class="card-body">
                     {{ include('etudiant/_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/etudiant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etudiant{% endblock %}

{% block body %}
    <h1>Etudiant</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ etudiant.id }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ etudiant.status ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Cne</th>
                <td>{{ etudiant.cne }}</td>
            </tr>
            <tr>
                <th>Cin</th>
                <td>{{ etudiant.cin }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ etudiant.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ etudiant.prenom }}</td>
            </tr>
            <tr>
                <th>Date_Naissance</th>
                <td>{{ etudiant.dateNaissance ? etudiant.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ etudiant.telephone }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ etudiant.email }}</td>
            </tr>
            <tr>
                <th>Genre</th>
                <td>{{ etudiant.genre }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ etudiant.ville }}</td>
            </tr>
            <tr>
                <th>Adresse_postale</th>
                <td>{{ etudiant.adressePostale }}</td>
            </tr>
            <tr>
                <th>Nationalite</th>
                <td>{{ etudiant.nationalite }}</td>
            </tr>
            <tr>
                <th>Profession_pere</th>
                <td>{{ etudiant.professionPere }}</td>
            </tr>
            <tr>
                <th>Profession_mere</th>
                <td>{{ etudiant.professionMere }}</td>
            </tr>
            <tr>
                <th>Gsm_mere</th>
                <td>{{ etudiant.gsmMere }}</td>
            </tr>
            <tr>
                <th>Gsm_pere</th>
                <td>{{ etudiant.gsmPere }}</td>
            </tr>
            <tr>
                <th>Mot_passe</th>
                <td>{{ etudiant.motPasse }}</td>
            </tr>
            <tr>
                <th>Confirm_pass</th>
                <td>{{ etudiant.ConfirmPass }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_etudiant_index') }}">back to list</a>

    <a href="{{ path('app_etudiant_edit', {'id': etudiant.id}) }}">edit</a>

    {{ include('etudiant/_delete_form.html.twig') }}
{% endblock %}